### ISSUE TITLE
error.Can you help me ?

### ISSUE THREAD

**Issue by fengshengchina** [meeki007/node-red-contrib-facial-recognition#24]
27 Nov 01:29:29 - [error] [facial-recognition:674fa2c4.b218a4] Error: ENOENT: no such file or directory, scandir 'c:\face\labeled_face\c:\face\labeled_face\emily willis'
27 Nov 01:29:29 - [red] Uncaught Exception:
27 Nov 01:29:29 - [error] TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Users\han\.node-red\node_modules\node-red-contrib-facial-recognition\facial-recognition.js:376:57
    at async Promise.all (index 0)
    at facialrecognitionNode._inputCallback (C:\Users\han\.node-red\node_modules\node-red-contrib-facial-recognition\facial-recognition.js:882:48)

C:\Users\han>

**Comment by meeki007** [comment]
I can try....but my brain is trying to remember code I wrote 2 years ago.....
I can tell your running on windows.......I have not used windows in 20 years. 


scandir 'c:\face\labeled_face\c:\face\labeled_face\emily willis'
can I get your flow file? I think your imputing the location of files incorrectly. 
Can you check that ?

**Comment by fengshengchina** [comment]
[
    {
        "id": "201a641e2840104c",
        "type": "tab",
        "label": "face_recognize",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "4a6f83b90246e18a",
        "type": "inject",
        "z": "201a641e2840104c",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 500,
        "wires": [
            [
                "a0dc64f1218d9c49"
            ]
        ]
    },
    {
        "id": "a0dc64f1218d9c49",
        "type": "file in",
        "z": "201a641e2840104c",
        "name": "",
        "filename": "c:/users/han/.node-red/node_modules/node-red-contrib-facial-recognition/example/unknown_face/sample (1).jpg",
        "filenameType": "str",
        "format": "",
        "chunk": false,
        "sendError": false,
        "encoding": "none",
        "allProps": false,
        "x": 730,
        "y": 540,
        "wires": [
            [
                "fd1a09c4ab364cfd"
            ]
        ]
    },
    {
        "id": "c8152c6a3b70819b",
        "type": "debug",
        "z": "201a641e2840104c",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 320,
        "y": 580,
        "wires": []
    },
    {
        "id": "fd1a09c4ab364cfd",
        "type": "facial-recognition",
        "z": "201a641e2840104c",
        "image": "payload",
        "settings": "settings",
        "name": "",
        "bindings": "CPU",
        "FaceDetector": "SsdMobilenetv1",
        "FaceDetector_SsdMobilenetv1_maxResults": "1",
        "FaceDetector_SsdMobilenetv1_minConfidence": "0.6",
        "FaceDetector_tinyFaceDetector_inputSize": "416",
        "FaceDetector_tinyFaceDetector_scoreThreshold": ".4",
        "Tasks": "detectSingleFace",
        "FaceLandmarks": true,
        "FaceExpressions": true,
        "AgeAndGender": true,
        "FaceDescriptors": true,
        "Face_Recognition": "Face_Recognition_enabled",
        "Face_Recognition_enabled_path": "FullPathToLabeledFaces",
        "Face_Recognition_distanceThreshold": 0.7,
        "x": 160,
        "y": 580,
        "wires": [
            [
                "c8152c6a3b70819b"
            ]
        ]
    },
    {
        "id": "d14163884da0e2d3",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "Recognize a single face in image",
        "info": "",
        "x": 160,
        "y": 380,
        "wires": []
    },
    {
        "id": "e2c8b588cda536b5",
        "type": "inject",
        "z": "201a641e2840104c",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 150,
        "y": 240,
        "wires": [
            [
                "e4ce6440b5ba9867"
            ]
        ]
    },
    {
        "id": "e4ce6440b5ba9867",
        "type": "file in",
        "z": "201a641e2840104c",
        "name": "",
        "filename": "c:/face/sample (1).jpg",
        "filenameType": "str",
        "format": "",
        "chunk": false,
        "sendError": false,
        "encoding": "none",
        "allProps": false,
        "x": 450,
        "y": 280,
        "wires": [
            [
                "ad8f23ce0a3d6a57"
            ]
        ]
    },
    {
        "id": "6d21475a964a61cd",
        "type": "debug",
        "z": "201a641e2840104c",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 320,
        "y": 320,
        "wires": []
    },
    {
        "id": "ad8f23ce0a3d6a57",
        "type": "facial-recognition",
        "z": "201a641e2840104c",
        "image": "payload",
        "settings": "settings",
        "name": "",
        "bindings": "CPU",
        "FaceDetector": "SsdMobilenetv1",
        "FaceDetector_SsdMobilenetv1_maxResults": "5",
        "FaceDetector_SsdMobilenetv1_minConfidence": "0.6",
        "FaceDetector_tinyFaceDetector_inputSize": "416",
        "FaceDetector_tinyFaceDetector_scoreThreshold": ".4",
        "Tasks": "detectAllFaces",
        "FaceLandmarks": true,
        "FaceExpressions": true,
        "AgeAndGender": true,
        "FaceDescriptors": true,
        "Face_Recognition": "Face_Recognition_enabled",
        "Face_Recognition_enabled_path": "c:\\\\face\\\\labeled_face\\\\",
        "Face_Recognition_distanceThreshold": 0.7,
        "x": 160,
        "y": 320,
        "wires": [
            [
                "6d21475a964a61cd"
            ]
        ]
    },
    {
        "id": "7dcc5005adf27141",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "Recognize all faces in image",
        "info": "",
        "x": 150,
        "y": 120,
        "wires": []
    },
    {
        "id": "a606e34d98dab2b4",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "Note: you will notice it takes longer the first time as it has to load all images",
        "info": "",
        "x": 330,
        "y": 160,
        "wires": []
    },
    {
        "id": "f9aadcb22e893d87",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "the next time you run it it should take less time",
        "info": "",
        "x": 240,
        "y": 200,
        "wires": []
    },
    {
        "id": "19a031490cacc2fc",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "Note: you will notice it takes longer the first time as it has to load all images",
        "info": "",
        "x": 330,
        "y": 420,
        "wires": []
    },
    {
        "id": "08808fbf4cc98814",
        "type": "comment",
        "z": "201a641e2840104c",
        "name": "the next time you run it it should take less time",
        "info": "",
        "x": 240,
        "y": 460,
        "wires": []
    }
]

**Comment by fengshengchina** [comment]
Thank you very much!
My imputing the location of files is correct.
C:/face/labeled_face/emily willis
C:/face/labeled_face/jessica smith
C:/face/labeled_face/laura tilling
C:/face/labeled_face/tara sanford
C:/face/unknown_face

Use “C:/users/han/.nodered/node_modules/node-red-contrib-facial-recognition/example/labeled_face/emily willis” ,not OK.

Best Regards !

发件人: meeki007 ***@***.***
发送时间: 2022年11月27日 5:33
收件人: meeki007/node-red-contrib-facial-recognition ***@***.***>
抄送: 韩风生 ***@***.***>; Author ***@***.***>
主题: Re: [meeki007/node-red-contrib-facial-recognition] error.Can you help me ? (Issue #24)


I can try....but my brain is trying to remember code I wrote 2 years ago.....
I can tell your running on windows.......I have not used windows in 20 years.

scandir 'c:\face\labeled_face\c:\face\labeled_face\emily willis'
can I get your flow file? I think your imputing the location of files incorrectly.
Can you check that ?
